<?php

// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-04-01 18:47

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('piwikintegration');
$extensionClassesPath = $extensionPath.'Classes/';

return [
    'tx_piwikintegration_config'                  => $extensionClassesPath.'Lib/Config.php',
    'tx_piwikintegration_div'                     => $extensionClassesPath.'Lib/Div.php',
    'tx_piwikintegration_extmgm'                  => $extensionClassesPath.'Lib/Extmgm.php',
    'tx_piwikintegration_flexform'                => $extensionPath.'pi1/class.tx_piwikintegration_flexform.php',
    'tx_piwikintegration_hooks_beuserprocessing'  => $extensionClassesPath.'Hooks/BeUserProcessing.php',
    'tx_piwikintegration_install'                 => $extensionClassesPath.'Lib/Install.php',
    'tx_piwikintegration_module1'                 => $extensionPath.'mod1/index.php',
    'tx_piwikintegration_pi1'                     => $extensionPath.'pi1/class.tx_piwikintegration_pi1.php',
    'tx_piwikintegration_pi1_templavoila_preview' => $extensionPath.'pi1/class.tx_piwikintegration_pi1_templavoila_preview.php',
    'tx_piwikintegration_pi1_wizicon'             => $extensionPath.'pi1/class.tx_piwikintegration_pi1_wizicon.php',
    'tx_piwikintegration_scheduler_archive'       => $extensionClassesPath.'SchedulerTasks/Archive.php',
    'tx_piwikintegration_tracking'                => $extensionClassesPath.'Tracking/Tracking.php',
];
